theme: jekyll-theme-cayman
title: Annotating Images with TensorFlow Object Detection API
description: This project presents a quick and easy way to detect, classify and localize objects in images and videos using the TensorFlow Object Detection API<br>Felix Le<br>March 2019
Felix Le Hong Phuoc
March 2019
